# Generated by Django 3.1.2 on 2021-04-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='gray',
            new_name='result',
        ),
    ]
